# Generated by Django 5.1.5 on 2025-02-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='tags',
            name='blogPost',
        ),
        migrations.AlterField(
            model_name='tags',
            name='text',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='blogPost',
            field=models.ManyToManyField(related_name='tags', to='main.blogpost'),
        ),
    ]
